const $=id=>document.getElementById(id);
let authorization=false, recordings=[], shown=[], page=0, audioUrl='', audioRequest=null, listRequest=null, loadSequence=0, playSequence=0;
let loadedContext=null, editing=null, playing=null, savingNotes=false, reviewing=false;
let agentRequest=null,agentSequence=0,agentsDate='';
let refreshing=false,noteRevision=0,autoRefresh=true,refreshSeconds=120,refreshTimer=null;
const size=50;
const params=new URLSearchParams(location.search);
$('agent').value=params.get('u')||'lnacional';
const today=new Date();
$('date').value=params.get('q')||[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
function originalUrl(){const u=new URL('https://myvici.info/admin/agentRecordingsLessThan30.php');u.searchParams.set('u',$('agent').value);u.searchParams.set('q',$('date').value);return u.href;}
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
function renderNote(target,notes,prefix='',empty=''){target.replaceChildren();const text=String(notes||'');if(!text){target.textContent=empty;return;}if(prefix)target.append(document.createTextNode(prefix));let start=0;for(const match of text.matchAll(/\b(?:not\s+sure|not\s+valid|invalid|valid)\b/gi)){target.append(document.createTextNode(text.slice(start,match.index)));const tag=document.createElement('span');tag.className='note-tag '+(/^not\s+sure$/i.test(match[0])?'note-unsure':/^(?:invalid|not\s+valid)$/i.test(match[0])?'note-invalid':'note-valid');tag.textContent=match[0];target.append(tag);start=match.index+match[0].length;}target.append(document.createTextNode(text.slice(start)));}
function editNotes(record,queueReview=false){if(!loadedContext||savingNotes)return;editing=record;reviewing=queueReview;$('save-next').hidden=!queueReview;$('invalid-reason').value=invalidReason(record.notes);$('history-list').replaceChildren();$('review-history').open=false;$('verdict-controls').hidden=String(record.status).toUpperCase()!=='XFER';$('review-audio').hidden=!queueReview;$('notes-customer').textContent=record.customer;$('notes-detail').textContent=`Lead ${record.lead} · ${record.time} · ${loadedContext.agent} · ${loadedContext.date}`;$('notes-text').value=record.notes||'';$('notes-status').textContent='';$('notes-status').className='';syncVerdict();if(!$('notes-dialog').open)$('notes-dialog').showModal();$('notes-text').focus();}
function closeNotes(){if(savingNotes)return false;if(editing&&$('notes-text').value!==(editing.notes||'')&&!confirm('Discard your unsaved note changes?'))return false;finishReview();return true;}
function audioMessage(text){$('audio-status').textContent=text;$('review-audio-status').textContent=text;}
function finishReview(){if(reviewing){stopAudio();$('player-panel').insertBefore($('player'),$('recording-notes'));$('player-panel').insertBefore($('playback-controls'),$('recording-notes'));}reviewing=false;$('review-audio').hidden=true;$('notes-dialog').close();editing=null;}
function syncVerdict(){const verdict=noteVerdict($('notes-text').value);$('mark-valid').setAttribute('aria-pressed',String(verdict==='valid'));$('mark-invalid').setAttribute('aria-pressed',String(verdict==='invalid'));$('mark-unsure').setAttribute('aria-pressed',String(verdict==='unsure'));$('invalid-reason-label').hidden=verdict!=='invalid';$('verdict-status').textContent=verdict==='unreviewed'?'Not reviewed':verdict==='valid'?'Valid transfer':verdict==='unsure'?'Needs further review':'Invalid transfer';}
function reviewCandidates(){return selectRecordings(recordings,$('search').value,'',$('time-sort').value,'unreviewed');}
function reviewCall(record){if(savingNotes||!record)return;editNotes(record,true);$('review-audio').append($('player'),$('playback-controls'));play(record,null);$('player-panel').hidden=true;}
function advanceReview(record,queue){const remaining=reviewCandidates();const position=queue.indexOf(record);const next=queue.slice(position+1).find(r=>remaining.includes(r))||remaining.find(r=>r!==record);if(next)reviewCall(next);else{finishReview();message('Review queue complete. All matching XFER calls have a review label.');}}
function saveBusy(busy){for(const id of ['save-notes','save-next','cancel-notes','notes-text','mark-valid','mark-invalid','mark-unsure','invalid-reason'])$(id).disabled=busy;}
async function saveNotes(advance=false){if(!editing||savingNotes||!authorization||!loadedContext)return;const record=editing,context={...loadedContext},notes=$('notes-text').value;const queue=advance?reviewCandidates():[];if(advance&&noteVerdict(notes)==='unreviewed'){$('notes-status').textContent='Choose Valid, Invalid or Not sure before continuing.';return;}if(notes===(record.notes||'')){if(advance){advanceReview(record,queue);return;}$('notes-status').textContent='No changes to save.';return;}let confirmed=false;savingNotes=true;saveBusy(true);$('notes-status').className='';$('notes-status').textContent='Saving notes…';try{const response=await fetch('/api/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead:record.lead,audio:record.audio,agent:context.agent,date:context.date,notes})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save notes.');if(!result.saved){$('notes-status').textContent=result.message||'The server did not confirm this save. Your draft is kept here.';return;}confirmed=true;noteRevision++;record.notes=notes;filter(false);if(playing===record)renderNote($('recording-notes'),notes,'Notes: ');$('notes-status').className='success';$('notes-status').textContent=result.historyWarning?'Notes saved. '+result.historyWarning:'Notes saved.';invalidateTeam();}catch(e){$('notes-status').className='error';$('notes-status').textContent=(e.message||'Could not confirm the save.')+' Your draft is kept here.';}finally{savingNotes=false;saveBusy(false);}if(advance&&confirmed)advanceReview(record,queue);}

function stopAudio(){playSequence++;audioRequest?.abort();$('player').pause();$('player').removeAttribute('src');$('player').load();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl='';$('player-panel').hidden=true;document.querySelectorAll('tr.selected').forEach(r=>r.classList.remove('selected'));}
function showLogin(){resetReports();authorization=false;agentSequence++;agentRequest?.abort();agentsDate='';$('agent-picker').replaceChildren(new Option('Connect to load agents',''));$('agents-message').textContent='';loadSequence++;listRequest?.abort();stopAudio();recordings=[];shown=[];$('rows').replaceChildren();$('results').hidden=true;$('connection').hidden=false;$('workspace').hidden=true;document.body.classList.add('signed-out');$('disconnect').hidden=true;$('username').value='';$('password').value='';message('Connect above to load recordings.');}
function render(){const max=Math.max(1,Math.ceil(shown.length/size));page=Math.max(0,Math.min(page,max-1));$('rows').replaceChildren();for(const r of shown.slice(page*size,(page+1)*size)){const tr=document.createElement('tr');if(r===playing&&audioUrl)tr.classList.add('selected');for(const [i,value] of [r.lead,r.time,r.customer,r.status,r.seconds+'s',r.hangup,r.campaign].entries()){const td=document.createElement('td');if(i===0){const a=document.createElement('a');a.href='https://myvici.info/vicidial/admin_modify_lead.php?lead_id='+encodeURIComponent(r.lead);a.target='_blank';a.rel='noopener noreferrer';a.textContent=value;td.append(a);}else if(i===3){const span=document.createElement('span');span.textContent=value;td.append(span);}else td.textContent=value;tr.append(td);}const playCell=document.createElement('td'),button=document.createElement('button');button.textContent='Play';button.setAttribute('aria-label','Play recording for '+r.customer+' at '+r.time);button.onclick=()=>play(r,tr);playCell.append(button);tr.append(playCell);const notes=document.createElement('td');const preview=document.createElement('div');preview.className='note-preview';renderNote(preview,r.notes,'','—');const edit=document.createElement('button');edit.type='button';edit.className='note-edit';edit.textContent='Edit notes';edit.setAttribute('aria-label','Edit notes for '+r.customer+' at '+r.time);edit.onclick=()=>editNotes(r);notes.append(preview,edit);notes.style.maxWidth='220px';notes.style.whiteSpace='normal';tr.append(notes);$('rows').append(tr);}if(!shown.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=9;td.textContent='No recordings match.';tr.append(td);$('rows').append(tr);}$('count').textContent=shown.length.toLocaleString()+' recordings';$('page-info').textContent=shown.length?`${page*size+1}–${Math.min((page+1)*size,shown.length)} of ${shown.length.toLocaleString()}`:'0 recordings';$('previous').disabled=page===0;$('next').disabled=page>=max-1;}
function updateStatuses(){const previous=$('status-filter').value||pendingStatus;pendingStatus='';$('status-filter').replaceChildren(new Option('All statuses',''));for(const status of [...new Set(recordings.map(r=>r.status).filter(Boolean))].sort())$('status-filter').add(new Option(status,status));$('status-filter').disabled=$('review-queue').checked;$('status-filter').value=[...$('status-filter').options].some(o=>o.value===previous)?previous:'';}
function filter(resetPage=true){shown=selectRecordings(recordings,$('search').value,$('status-filter').value,$('time-sort').value,$('review-queue').checked?'unreviewed':$('further-review').checked?'unsure':'all');if(resetPage)page=0;const counts=transferCounts(recordings);for(const key of ['total','valid','invalid','unsure','unreviewed'])$('transfers-'+key).textContent=counts[key].toLocaleString();$('transfer-scope').textContent=loadedContext?`Loaded XFER calls · ${loadedContext.agent} · ${loadedContext.date}`:'Loaded XFER calls';$('queue-count').textContent=reviewCandidates().length.toLocaleString()+' unreviewed XFER';$('review-next').disabled=reviewCandidates().length===0;render();}
async function loadAgents(){agentRequest?.abort();const controller=new AbortController();agentRequest=controller;const seq=++agentSequence;const date=$('date').value;if(!authorization||!date)return;agentsDate='';$('agent-picker').disabled=true;$('agents-message').textContent='Loading agents…';try{const response=await fetch('/api/agents?'+new URLSearchParams({date}),{signal:controller.signal});const data=await response.json();if(seq!==agentSequence)return;if(!response.ok)throw new Error(data.error||'Could not load agents.');agentsDate=date;$('agent-picker').replaceChildren(new Option('Choose an agent…',''));for(const a of data.agents)$('agent-picker').add(new Option(a.name,a.username));$('agent-picker').value=$('agent').value;$('agents-message').textContent=`${data.agents.length} agents · ${date} · Agent roster`;}catch(e){if(e.name!=='AbortError'&&seq===agentSequence){$('agent-picker').replaceChildren(new Option('Agent list unavailable',''));$('agents-message').textContent=(e.message||'Could not load agents.')+' Enter an agent username to continue.';}}finally{if(seq===agentSequence)$('agent-picker').disabled=false;}}
async function load(){if(savingNotes){message('Finish saving the note before changing agents.',true);return;}if(editing&&!closeNotes())return;if(!authorization){message('Connect to MyVici first.');$('username').focus();return;}if(!$('filters').reportValidity())return;resetReports();listRequest?.abort();const controller=new AbortController();listRequest=controller;const seq=++loadSequence;stopAudio();loadedContext=null;recordings=[];shown=[];$('rows').replaceChildren();$('results').hidden=true;$('original').href=originalUrl();$('load').disabled=true;message('Loading the recording list…');const start=performance.now();try{const url=new URL('/api/recordings',location.origin);url.searchParams.set('u',$('agent').value);url.searchParams.set('q',$('date').value);const res=await fetch(url,{signal:controller.signal});const data=await res.json();if(seq!==loadSequence)return;if(!res.ok)throw new Error(data.error||'Could not load recordings.');const viewUrl=new URL(location.href);viewUrl.searchParams.set('u',url.searchParams.get('u'));viewUrl.searchParams.set('q',url.searchParams.get('q'));history.replaceState(null,'',viewUrl);recordings=data.recordings;loadedContext={agent:url.searchParams.get('u'),date:url.searchParams.get('q')};$('agent-name').textContent=data.agent||$('agent').value;$('connection').hidden=true;$('workspace').hidden=false;document.body.classList.remove('signed-out');$('disconnect').hidden=false;$('results').hidden=false;updateStatuses();filter();$('sync-status').textContent=autoRefresh?'Auto refresh every '+refreshSeconds+' seconds · Waiting for the next check':'Manual mode · Use Refresh now to check for recordings';message(`${recordings.length.toLocaleString()} recordings loaded in ${((performance.now()-start)/1000).toFixed(1)}s. Select Play to load audio.`);}catch(e){if(e.name!=='AbortError'&&seq===loadSequence)message(e.message,true);}finally{if(seq===loadSequence)$('load').disabled=false;}}
async function play(r,tr){stopAudio();playing=r;const seq=playSequence;const controller=new AbortController();audioRequest=controller;tr?.classList.add('selected');$('player-panel').hidden=false;$('playing-name').textContent=r.customer;$('playing-detail').textContent=`Lead ${r.lead} · ${r.time} · ${r.seconds}s · ${r.status} · ${r.hangup}`;renderNote($('recording-notes'),r.notes,'Notes: ');audioMessage('Loading selected recording…');try{const url=new URL('/api/audio',location.origin);url.searchParams.set('path',r.audio);const res=await fetch(url,{signal:controller.signal});if(!res.ok){let detail;try{detail=await res.json();}catch{}throw new Error(detail?.error||'Recording unavailable.');}const blob=await res.blob();if(seq!==playSequence)return;audioUrl=URL.createObjectURL(blob);$('player').src=audioUrl;$('player').playbackRate=Number($('playback-speed').value);audioMessage('Ready to play');try{await $('player').play();}catch{audioMessage('Ready — press Play in the audio player.');}}catch(e){if(e.name!=='AbortError'&&seq===playSequence)audioMessage(e.message);}}
function showDashboard(){authorization=true;$('connection').hidden=true;$('workspace').hidden=false;$('disconnect').hidden=false;document.body.classList.remove('signed-out');loadAgents();load();}
async function disconnect(){if(savingNotes||(editing&&!closeNotes()))return;try{const response=await fetch('/api/logout',{method:'POST'});if(!response.ok)throw new Error();showLogin();$('login-status').textContent='You have been signed out.';}catch{message('Could not sign out. Try again.',true);}}
$('show-password').onclick=()=>{const hidden=$('password').type==='password';$('password').type=hidden?'text':'password';$('show-password').textContent=hidden?'Hide':'Show';$('show-password').setAttribute('aria-label',hidden?'Hide password':'Show password');};
$('login').onsubmit=async e=>{e.preventDefault();$('sign-in').disabled=true;$('login-status').className='';$('login-status').textContent='Checking your credentials…';try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value,date:$('date').value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not sign in.');$('password').value='';showDashboard();}catch(error){$('login-status').className='error';$('login-status').textContent=error.message;}finally{$('sign-in').disabled=false;}};
async function restoreSession(){document.body.classList.add('signed-out');$('login-status').textContent='Checking your session…';$('sign-in').disabled=true;try{const response=await fetch('/api/session');if(response.ok){$('login-status').textContent='';showDashboard();}else $('login-status').textContent='';}catch{$('login-status').textContent='Could not check your session. You can try signing in.';}finally{$('sign-in').disabled=false;}}
restoreSession();
$('filters').onsubmit=e=>{e.preventDefault();if(agentsDate!==$('date').value)loadAgents();load();};$('date').onchange=()=>loadAgents();$('agent-picker').onchange=()=>{const username=$('agent-picker').value;if(!username)return;if(savingNotes||(editing&&!closeNotes())){$('agent-picker').value=loadedContext?.agent||$('agent').value;return;}$('agent').value=username;$('search').value='';load();};$('agent').oninput=()=>{$('agent-picker').value=$('agent').value;};$('search').oninput=()=>filter();$('status-filter').onchange=()=>filter();$('time-sort').onchange=()=>filter();$('previous').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('close-player').onclick=stopAudio;$('disconnect').onclick=disconnect;$('player').onerror=()=>{audioMessage('This recording could not be played.');};$('original').href=originalUrl();
$('notes-form').onsubmit=e=>{e.preventDefault();saveNotes();};$('save-next').onclick=()=>saveNotes(true);$('notes-text').oninput=syncVerdict;for(const verdict of ['valid','invalid','unsure'])$('mark-'+verdict).onclick=()=>{const notes=setNoteVerdict($('notes-text').value,verdict);if(notes.length>4000){$('notes-status').textContent='Shorten this note to make room for the review label.';return;}$('notes-text').value=notes;syncVerdict();};$('review-queue').onchange=()=>{$('status-filter').value='';$('status-filter').disabled=$('review-queue').checked;filter();};$('review-next').onclick=()=>reviewCall(reviewCandidates()[0]);$('cancel-notes').onclick=closeNotes;$('notes-dialog').addEventListener('cancel',e=>{e.preventDefault();closeNotes();});$('edit-playing-notes').onclick=()=>{if(playing)editNotes(playing);};
if(document.modelContext?.registerTool){for(const tool of [{name:'get_recording_list',description:'Read the currently loaded and filtered recordings without playing audio.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({total:shown.length,page:page+1,recordings:shown.slice(page*size,(page+1)*size).map(({audio,...r})=>r)})},{name:'filter_recordings',description:'Filter the already loaded recording list by customer, lead, status, or time.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.query!=='string'||Object.keys(input).some(k=>k!=='query'))throw new Error('Provide a query string.');$('search').value=input.query;filter();return {total:shown.length};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}



async function refreshRecordings(manual=false){
 if(reportController||(!manual&&!autoRefresh)||refreshing||!authorization||!loadedContext||document.hidden||$('load').disabled)return;
 if(editing||savingNotes){if(manual)$('sync-status').textContent='Finish reviewing or saving this note before refreshing.';return;}
 const context=loadedContext,seq=loadSequence,revision=noteRevision;refreshing=true;$('refresh-now').disabled=true;$('refresh-now').textContent='Refreshing…';
 $('sync-status').textContent='Checking for new recordings…';
 try{
 const res=await fetch('/api/recordings?'+new URLSearchParams({u:context.agent,q:context.date}),{cache:'no-store',signal:AbortSignal.timeout(20000)});
 const data=await res.json();
 if(seq!==loadSequence||context!==loadedContext||!authorization)return;
 if(!res.ok)throw new Error(data.error||'Recording check failed.');
 if(editing||savingNotes||revision!==noteRevision){$('sync-status').textContent='Auto refresh paused during note review · Your draft is preserved';return;}
 if(!Array.isArray(data.recordings))throw new Error('Unexpected recording response.');
 const changed=JSON.stringify(recordings)!==JSON.stringify(data.recordings);
 if(changed){invalidateTeam();recordings=mergeRecordingRefresh(recordings,data.recordings);updateStatuses();filter(false);message(recordings.length.toLocaleString()+' recordings loaded. New recordings are checked automatically.');if(playing)renderNote($('recording-notes'),playing.notes,'Notes: ');}
 $('sync-status').textContent=(autoRefresh?'Auto refresh every '+refreshSeconds+' seconds':'Manual refresh')+' · Checked '+new Date().toLocaleTimeString()+ (changed?' · Recordings updated':'');
 if(agentsDate===context.date&&$('date').value===context.date){
 try{const response=await fetch('/api/agents?'+new URLSearchParams({date:context.date}),{cache:'no-store',signal:AbortSignal.timeout(20000)});const roster=await response.json();
 if(response.ok&&seq===loadSequence&&context===loadedContext&&$('date').value===context.date&&!$('agent-picker').disabled&&Array.isArray(roster.agents)){
 const selected=$('agent-picker').value;$('agent-picker').replaceChildren(new Option('Choose an agent…',''));
 for(const agent of roster.agents)$('agent-picker').add(new Option(agent.name,agent.username));$('agent-picker').value=selected;
 $('agents-message').textContent=roster.agents.length+' agents · '+context.date+' · Agent roster';
 }}catch{ /* Keep the last roster if the summary is temporarily unavailable. */ }
 }
 }catch(error){if(seq===loadSequence&&context===loadedContext&&authorization)$('sync-status').textContent='Auto refresh could not check · '+error.message+' Retrying in '+refreshSeconds+' seconds.';}
 finally{refreshing=false;$('refresh-now').disabled=false;$('refresh-now').textContent='Refresh now';}
}
function scheduleRefresh(){clearInterval(refreshTimer);if(autoRefresh)refreshTimer=setInterval(refreshRecordings,refreshSeconds*1000);}
scheduleRefresh();
$('refresh-interval').onchange=()=>{const seconds=Number($('refresh-interval').value);if(![30,60,120,300,600].includes(seconds))return;refreshSeconds=seconds;scheduleRefresh();$('sync-status').textContent=autoRefresh?'Auto refresh every '+refreshSeconds+' seconds':'Manual mode · Use Refresh now to check for recordings';};
$('auto-refresh').onclick=()=>{autoRefresh=!autoRefresh;scheduleRefresh();$('auto-refresh').setAttribute('aria-checked',String(autoRefresh));$('auto-refresh').textContent=autoRefresh?'Auto':'Manual';$('sync-status').textContent=autoRefresh?'Auto refresh every '+refreshSeconds+' seconds':'Manual mode · Use Refresh now to check for recordings';};
$('further-review').onchange=()=>{if($('further-review').checked){$('review-queue').checked=false;$('status-filter').value='';$('status-filter').disabled=false;}filter();};
$('review-queue').addEventListener('change',()=>{if($('review-queue').checked)$('further-review').checked=false;filter();});
$('refresh-now').onclick=()=>refreshRecordings(true);

let teamData=null,teamVersion=0,reportController=null,reportBlobUrl='';
function resetReports(){reportController?.abort();if(reportBlobUrl)URL.revokeObjectURL(reportBlobUrl);reportBlobUrl='';$('report-preview').hidden=true;$('report-text').textContent='';$('report-status').textContent='';invalidateTeam();}
function invalidateTeam(){teamVersion++;teamData=null;$('team-results').hidden=true;}
$('invalid-reason').onchange=()=>{const notes=setInvalidReason($('notes-text').value,$('invalid-reason').value);if(notes.length>4000){$('notes-status').textContent='Shorten the note to add this reason.';return;}$('notes-text').value=notes;syncVerdict();};
$('playback-speed').onchange=()=>{$('player').playbackRate=Number($('playback-speed').value);rememberPreferences();};
function skipAudio(seconds){const player=$('player');if(!Number.isFinite(player.duration))return;player.currentTime=Math.min(player.duration,Math.max(0,player.currentTime+seconds));}
$('skip-back').onclick=()=>skipAudio(-10);$('skip-forward').onclick=()=>skipAudio(10);
function rememberPreferences(){try{localStorage.setItem('qa-preferences',JSON.stringify({autoRefresh,refreshSeconds,status:$('status-filter').value,sort:$('time-sort').value,search:$('search').value,queue:$('review-queue').checked,further:$('further-review').checked,speed:$('playback-speed').value}));}catch{}}
function restorePreferences(){try{const p=JSON.parse(localStorage.getItem('qa-preferences')||'null');if(!p||typeof p!=='object')return;if(typeof p.autoRefresh==='boolean')autoRefresh=p.autoRefresh;if([30,60,120,300,600].includes(p.refreshSeconds))refreshSeconds=p.refreshSeconds;$('refresh-interval').value=String(refreshSeconds);$('auto-refresh').setAttribute('aria-checked',String(autoRefresh));$('auto-refresh').textContent=autoRefresh?'Auto':'Manual';if(['original','earliest','latest'].includes(p.sort))$('time-sort').value=p.sort;if(typeof p.search==='string')$('search').value=p.search.slice(0,200);$('review-queue').checked=p.queue===true;$('further-review').checked=!$('review-queue').checked&&p.further===true;if(['0.75','1','1.25','1.5','2'].includes(p.speed))$('playback-speed').value=p.speed;pendingStatus=typeof p.status==='string'?p.status:'';scheduleRefresh();}catch{}}
let pendingStatus='';restorePreferences();
for(const id of ['refresh-interval','auto-refresh','status-filter','time-sort','search','review-queue','further-review'])$(id).addEventListener(id==='search'?'input':id==='auto-refresh'?'click':'change',rememberPreferences);
async function collectTeam(date,signal){const version=teamVersion;const response=await fetch('/api/agents?'+new URLSearchParams({date}),{signal});const roster=await response.json();if(!response.ok)throw new Error(roster.error||'Could not load agents.');const report=[];for(const [index,agent] of roster.agents.entries()){$('report-status').textContent='Loading '+(index+1)+' of '+roster.agents.length+' agents: '+agent.name;const response=await fetch('/api/recordings?'+new URLSearchParams({u:agent.username,q:date}),{signal});const data=await response.json();if(!response.ok||!Array.isArray(data.recordings))throw new Error('Could not load '+agent.name+'. '+(data.error||'No report was downloaded.'));report.push({...agent,recordings:data.recordings});}if(version===teamVersion)teamData={date,agents:report};return report;}
function showTeamProgress(agents){const host=$('team-results');host.replaceChildren();const table=document.createElement('table');const header=document.createElement('tr');for(const text of ['Agent','Transfers','Valid','Invalid','Not sure','Unreviewed','Reviewed']){const th=document.createElement('th');th.textContent=text;header.append(th);}table.append(header);for(const agent of agents){const counts=transferCounts(agent.recordings),row=document.createElement('tr');for(const value of [agent.name,counts.total,counts.valid,counts.invalid,counts.unsure,counts.unreviewed,counts.total?Math.round((counts.valid+counts.invalid)/counts.total*100)+'%':'—']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}table.append(row);}host.append(table);host.hidden=false;}
async function reportAction(progressOnly=false){if(reportController)return;if(editing||savingNotes){$('report-status').textContent='Finish reviewing this note before generating a report.';return;}if(!loadedContext)return;const context={...loadedContext};const all=progressOnly||$('report-agents').value==='all',format=$('report-format').value,scope=$('report-scope').value;const controller=new AbortController();reportController=controller;$('cancel-report').hidden=false;for(const id of ['export-report','team-progress'])$(id).disabled=true;try{const agents=all?await collectTeam(context.date,controller.signal):[{username:context.agent,name:$('agent-name').textContent,recordings:recordings.map(r=>({...r}))}];if(controller.signal.aborted)return;if(progressOnly){showTeamProgress(agents);$('report-status').textContent=agents.length+' agents · '+context.date+' · Counts from actual recording lists · Not sure remains pending';}else{const text=reviewReport(agents,context.date,format,scope);if(reportBlobUrl)URL.revokeObjectURL(reportBlobUrl);reportBlobUrl=URL.createObjectURL(new Blob([text],{type:format==='csv'?'text/csv;charset=utf-8':'text/plain;charset=utf-8'}));const link=$('report-download');link.href=reportBlobUrl;link.download='qa-'+(all?'all-agents':context.agent)+'-'+context.date+'.'+format;$('report-text').textContent=text;$('report-preview').hidden=false;$('report-preview').open=true;link.click();$('report-status').textContent='Report ready · '+agents.length+' agents · '+context.date;}}catch(error){$('report-status').textContent=error.name==='AbortError'?'Report cancelled.':error.message;}finally{reportController=null;$('cancel-report').hidden=true;for(const id of ['export-report','team-progress'])$(id).disabled=false;}}
$('export-report').onclick=()=>reportAction(false);$('team-progress').onclick=()=>reportAction(true);$('cancel-report').onclick=()=>reportController?.abort();
$('load-history').onclick=async()=>{if(!editing||!loadedContext)return;const record=editing,context=loadedContext;const host=$('history-list');host.textContent='Loading history…';try{const response=await fetch('/api/history?'+new URLSearchParams({lead:record.lead,audio:record.audio,agent:context.agent,date:context.date}));const data=await response.json();if(editing!==record)return;if(!response.ok)throw new Error(data.error||'History unavailable.');host.replaceChildren();if(!data.events.length)host.textContent='No changes recorded by this app yet.';for(const event of data.events){const item=document.createElement('div');item.className='history-event';const heading=document.createElement('strong');heading.textContent=event.reviewer+' · '+new Date(event.timestamp).toLocaleString();const before=document.createElement('pre');before.textContent='Before: '+(event.previousNotes===null?'Unavailable':event.previousNotes||'—');const after=document.createElement('pre');after.textContent='After: '+event.notes;item.append(heading,before,after);host.append(item);}}catch(error){if(editing===record)host.textContent=error.message;}};
