const $=id=>document.getElementById(id);
let authorization=false, recordings=[], shown=[], page=0, audioUrl='', audioRequest=null, listRequest=null, loadSequence=0, playSequence=0;
let loadedContext=null, editing=null, playing=null, savingNotes=false;
let agentRequest=null,agentSequence=0,agentsDate='';
const size=50;
const params=new URLSearchParams(location.search);
$('agent').value=params.get('u')||'lnacional';
const today=new Date();
$('date').value=params.get('q')||[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');
function originalUrl(){const u=new URL('https://myvici.info/admin/agentRecordingsLessThan30.php');u.searchParams.set('u',$('agent').value);u.searchParams.set('q',$('date').value);return u.href;}
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
function renderNote(target,notes,prefix='',empty=''){target.replaceChildren();const text=String(notes||'');if(!text){target.textContent=empty;return;}if(prefix)target.append(document.createTextNode(prefix));let start=0;for(const match of text.matchAll(/\b(?:not\s+valid|invalid|valid)\b/gi)){target.append(document.createTextNode(text.slice(start,match.index)));const tag=document.createElement('span');tag.className='note-tag '+(/^(?:invalid|not\s+valid)$/i.test(match[0])?'note-invalid':'note-valid');tag.textContent=match[0];target.append(tag);start=match.index+match[0].length;}target.append(document.createTextNode(text.slice(start)));}
function editNotes(record){if(!loadedContext||savingNotes)return;editing=record;$('notes-customer').textContent=record.customer;$('notes-detail').textContent=`Lead ${record.lead} · ${record.time} · ${loadedContext.agent} · ${loadedContext.date}`;$('notes-text').value=record.notes||'';$('notes-status').textContent='';$('notes-status').className='';$('notes-dialog').showModal();$('notes-text').focus();}
function closeNotes(){if(savingNotes)return false;if(editing&&$('notes-text').value!==(editing.notes||'')&&!confirm('Discard your unsaved note changes?'))return false;$('notes-dialog').close();editing=null;return true;}
async function saveNotes(){if(!editing||savingNotes||!authorization||!loadedContext)return;const record=editing,context={...loadedContext},notes=$('notes-text').value;if(notes===(record.notes||'')){$('notes-status').textContent='No changes to save.';return;}savingNotes=true;$('save-notes').disabled=true;$('cancel-notes').disabled=true;$('notes-text').disabled=true;$('notes-status').className='';$('notes-status').textContent='Saving notes…';try{const response=await fetch('/api/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead:record.lead,audio:record.audio,agent:context.agent,date:context.date,notes})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not save notes.');if(!result.saved){$('notes-status').textContent=result.message||'The server did not confirm this save. Your draft is kept here.';return;}record.notes=notes;filter(false);if(playing===record)renderNote($('recording-notes'),notes,'Notes: ');$('notes-status').className='success';$('notes-status').textContent='Notes saved.';}catch(e){$('notes-status').className='error';$('notes-status').textContent=(e.message||'Could not confirm the save.')+' Your draft is kept here.';}finally{savingNotes=false;$('save-notes').disabled=false;$('cancel-notes').disabled=false;$('notes-text').disabled=false;}}
function stopAudio(){playSequence++;audioRequest?.abort();$('player').pause();$('player').removeAttribute('src');$('player').load();if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl='';$('player-panel').hidden=true;document.querySelectorAll('tr.selected').forEach(r=>r.classList.remove('selected'));}
function showLogin(){authorization=false;agentSequence++;agentRequest?.abort();agentsDate='';$('agent-picker').replaceChildren(new Option('Connect to load agents',''));$('agents-message').textContent='';loadSequence++;listRequest?.abort();stopAudio();recordings=[];shown=[];$('rows').replaceChildren();$('results').hidden=true;$('connection').hidden=false;$('workspace').hidden=true;document.body.classList.add('signed-out');$('disconnect').hidden=true;$('username').value='';$('password').value='';message('Connect above to load recordings.');}
function render(){const max=Math.max(1,Math.ceil(shown.length/size));page=Math.max(0,Math.min(page,max-1));$('rows').replaceChildren();for(const r of shown.slice(page*size,(page+1)*size)){const tr=document.createElement('tr');for(const [i,value] of [r.lead,r.time,r.customer,r.status,r.seconds+'s',r.hangup,r.campaign].entries()){const td=document.createElement('td');if(i===0){const a=document.createElement('a');a.href='https://myvici.info/vicidial/admin_modify_lead.php?lead_id='+encodeURIComponent(r.lead);a.target='_blank';a.rel='noopener noreferrer';a.textContent=value;td.append(a);}else if(i===3){const span=document.createElement('span');span.textContent=value;td.append(span);}else td.textContent=value;tr.append(td);}const playCell=document.createElement('td'),button=document.createElement('button');button.textContent='Play';button.setAttribute('aria-label','Play recording for '+r.customer+' at '+r.time);button.onclick=()=>play(r,tr);playCell.append(button);tr.append(playCell);const notes=document.createElement('td');const preview=document.createElement('div');preview.className='note-preview';renderNote(preview,r.notes,'','—');const edit=document.createElement('button');edit.type='button';edit.className='note-edit';edit.textContent='Edit notes';edit.setAttribute('aria-label','Edit notes for '+r.customer+' at '+r.time);edit.onclick=()=>editNotes(r);notes.append(preview,edit);notes.style.maxWidth='220px';notes.style.whiteSpace='normal';tr.append(notes);$('rows').append(tr);}if(!shown.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=9;td.textContent='No recordings match.';tr.append(td);$('rows').append(tr);}$('count').textContent=shown.length.toLocaleString()+' recordings';$('page-info').textContent=shown.length?`${page*size+1}–${Math.min((page+1)*size,shown.length)} of ${shown.length.toLocaleString()}`:'0 recordings';$('previous').disabled=page===0;$('next').disabled=page>=max-1;}
function updateStatuses(){const previous=$('status-filter').value;$('status-filter').replaceChildren(new Option('All statuses',''));for(const status of [...new Set(recordings.map(r=>r.status).filter(Boolean))].sort())$('status-filter').add(new Option(status,status));$('status-filter').value=[...$('status-filter').options].some(o=>o.value===previous)?previous:'';}
function filter(resetPage=true){shown=selectRecordings(recordings,$('search').value,$('status-filter').value,$('time-sort').value);if(resetPage)page=0;const counts=transferCounts(recordings);for(const key of ['total','valid','invalid','unreviewed'])$('transfers-'+key).textContent=counts[key].toLocaleString();$('transfer-scope').textContent=loadedContext?`Loaded XFER calls · ${loadedContext.agent} · ${loadedContext.date}`:'Loaded XFER calls';render();}
async function loadAgents(){agentRequest?.abort();const controller=new AbortController();agentRequest=controller;const seq=++agentSequence;const date=$('date').value;if(!authorization||!date)return;agentsDate='';$('agent-picker').disabled=true;$('agents-message').textContent='Loading agents…';try{const response=await fetch('/api/agents?'+new URLSearchParams({date}),{signal:controller.signal});const data=await response.json();if(seq!==agentSequence)return;if(!response.ok)throw new Error(data.error||'Could not load agents.');agentsDate=date;$('agent-picker').replaceChildren(new Option('Choose an agent…',''));for(const a of data.agents)$('agent-picker').add(new Option(`${a.name} · ${a.transfers} XFER`,a.username));$('agent-picker').value=$('agent').value;$('agents-message').textContent=`${data.agents.length} agents · ${date} · XFER totals from daily summary`;}catch(e){if(e.name!=='AbortError'&&seq===agentSequence){$('agent-picker').replaceChildren(new Option('Agent list unavailable',''));$('agents-message').textContent=(e.message||'Could not load agents.')+' Enter an agent username to continue.';}}finally{if(seq===agentSequence)$('agent-picker').disabled=false;}}
async function load(){if(savingNotes){message('Finish saving the note before changing agents.',true);return;}if(editing&&!closeNotes())return;if(!authorization){message('Connect to MyVici first.');$('username').focus();return;}if(!$('filters').reportValidity())return;listRequest?.abort();const controller=new AbortController();listRequest=controller;const seq=++loadSequence;stopAudio();recordings=[];shown=[];$('rows').replaceChildren();$('results').hidden=true;$('original').href=originalUrl();$('load').disabled=true;message('Loading the recording list…');const start=performance.now();try{const url=new URL('/api/recordings',location.origin);url.searchParams.set('u',$('agent').value);url.searchParams.set('q',$('date').value);const res=await fetch(url,{signal:controller.signal});const data=await res.json();if(seq!==loadSequence)return;if(!res.ok)throw new Error(data.error||'Could not load recordings.');const viewUrl=new URL(location.href);viewUrl.searchParams.set('u',url.searchParams.get('u'));viewUrl.searchParams.set('q',url.searchParams.get('q'));history.replaceState(null,'',viewUrl);recordings=data.recordings;loadedContext={agent:url.searchParams.get('u'),date:url.searchParams.get('q')};$('agent-name').textContent=data.agent||$('agent').value;$('connection').hidden=true;$('workspace').hidden=false;document.body.classList.remove('signed-out');$('disconnect').hidden=false;$('results').hidden=false;updateStatuses();filter();message(`${recordings.length.toLocaleString()} recordings loaded in ${((performance.now()-start)/1000).toFixed(1)}s. Select Play to load audio.`);}catch(e){if(e.name!=='AbortError'&&seq===loadSequence)message(e.message,true);}finally{if(seq===loadSequence)$('load').disabled=false;}}
async function play(r,tr){stopAudio();playing=r;const seq=playSequence;const controller=new AbortController();audioRequest=controller;tr?.classList.add('selected');$('player-panel').hidden=false;$('playing-name').textContent=r.customer;$('playing-detail').textContent=`Lead ${r.lead} · ${r.time} · ${r.seconds}s · ${r.status} · ${r.hangup}`;renderNote($('recording-notes'),r.notes,'Notes: ');$('audio-status').textContent='Loading selected recording…';try{const url=new URL('/api/audio',location.origin);url.searchParams.set('path',r.audio);const res=await fetch(url,{signal:controller.signal});if(!res.ok){let detail;try{detail=await res.json();}catch{}throw new Error(detail?.error||'Recording unavailable.');}const blob=await res.blob();if(seq!==playSequence)return;audioUrl=URL.createObjectURL(blob);$('player').src=audioUrl;$('audio-status').textContent='Ready to play';try{await $('player').play();}catch{$('audio-status').textContent='Ready — press Play in the audio player.';}}catch(e){if(e.name!=='AbortError'&&seq===playSequence)$('audio-status').textContent=e.message;}}
function showDashboard(){authorization=true;$('connection').hidden=true;$('workspace').hidden=false;$('disconnect').hidden=false;document.body.classList.remove('signed-out');loadAgents();load();}
async function disconnect(){if(savingNotes||(editing&&!closeNotes()))return;try{const response=await fetch('/api/logout',{method:'POST'});if(!response.ok)throw new Error();showLogin();$('login-status').textContent='You have been signed out.';}catch{message('Could not sign out. Try again.',true);}}
$('show-password').onclick=()=>{const hidden=$('password').type==='password';$('password').type=hidden?'text':'password';$('show-password').textContent=hidden?'Hide':'Show';$('show-password').setAttribute('aria-label',hidden?'Hide password':'Show password');};
$('login').onsubmit=async e=>{e.preventDefault();$('sign-in').disabled=true;$('login-status').className='';$('login-status').textContent='Checking your credentials…';try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value,date:$('date').value})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not sign in.');$('password').value='';showDashboard();}catch(error){$('login-status').className='error';$('login-status').textContent=error.message;}finally{$('sign-in').disabled=false;}};
async function restoreSession(){document.body.classList.add('signed-out');$('login-status').textContent='Checking your session…';$('sign-in').disabled=true;try{const response=await fetch('/api/session');if(response.ok){$('login-status').textContent='';showDashboard();}else $('login-status').textContent='';}catch{$('login-status').textContent='Could not check your session. You can try signing in.';}finally{$('sign-in').disabled=false;}}
restoreSession();
$('filters').onsubmit=e=>{e.preventDefault();if(agentsDate!==$('date').value)loadAgents();load();};$('date').onchange=()=>loadAgents();$('agent-picker').onchange=()=>{const username=$('agent-picker').value;if(!username)return;if(savingNotes||(editing&&!closeNotes())){$('agent-picker').value=loadedContext?.agent||$('agent').value;return;}$('agent').value=username;$('search').value='';load();};$('agent').oninput=()=>{$('agent-picker').value=$('agent').value;};$('search').oninput=()=>filter();$('status-filter').onchange=()=>filter();$('time-sort').onchange=()=>filter();$('previous').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('close-player').onclick=stopAudio;$('disconnect').onclick=disconnect;$('player').onerror=()=>{$('audio-status').textContent='This recording could not be played.';};$('original').href=originalUrl();
$('notes-form').onsubmit=e=>{e.preventDefault();saveNotes();};$('cancel-notes').onclick=closeNotes;$('notes-dialog').addEventListener('cancel',e=>{e.preventDefault();closeNotes();});$('edit-playing-notes').onclick=()=>{if(playing)editNotes(playing);};
if(document.modelContext?.registerTool){for(const tool of [{name:'get_recording_list',description:'Read the currently loaded and filtered recordings without playing audio.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({total:shown.length,page:page+1,recordings:shown.slice(page*size,(page+1)*size).map(({audio,...r})=>r)})},{name:'filter_recordings',description:'Filter the already loaded recording list by customer, lead, status, or time.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(typeof input?.query!=='string'||Object.keys(input).some(k=>k!=='query'))throw new Error('Provide a query string.');$('search').value=input.query;filter();return {total:shown.length};}}]){try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{});}catch{}}}


