import {mkdir,readFile,writeFile,rename,readdir} from 'node:fs/promises';
import {join} from 'node:path';import {createHash,randomUUID} from 'node:crypto';
export function createPayslipService(directory,ResponseType=Response){
 let writes=Promise.resolve();return async request=>{const reply=(body,status=200)=>new ResponseType(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});try{const url=new URL(request.url),owner=request.headers.get('X-Reviewer');if(!owner)return reply({error:'Missing reviewer.'},401);const root=join(directory,createHash('sha256').update(owner).digest('hex'));const id=url.searchParams.get('id');if(id&&!/^[a-f0-9-]{36}$/.test(id))return reply({error:'Invalid payslip ID.'},400);
 if(request.headers.get('X-Agent-Read')==='1'){
 if(request.method!=='GET'||url.searchParams.get('agent')!=='1')return reply({error:'Agent access is read-only.'},403);
 const publishedRoot=join(directory,'published',createHash('sha256').update(owner.toLowerCase()).digest('hex'));await writes.catch(()=>{});
 if(id){const entry=JSON.parse(await readFile(join(publishedRoot,id+'.json'),'utf8'));if(entry.snapshot.cutoff.agent.toLowerCase()!==owner.toLowerCase())return reply({error:'Payslip not found.'},404);return reply(entry);}
 let files;try{files=await readdir(publishedRoot);}catch(e){if(e.code!=='ENOENT')throw e;files=[];}const entries=[];for(const file of files.filter(f=>/^[a-f0-9-]{36}\.json$/.test(f))){const e=JSON.parse(await readFile(join(publishedRoot,file),'utf8'));if(e.snapshot.cutoff.agent.toLowerCase()===owner.toLowerCase())entries.push({id:e.id,createdAt:e.createdAt,start:e.snapshot.cutoff.start,end:e.snapshot.cutoff.end,currency:e.snapshot.currency});}return reply({entries:entries.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});
 }
 if(url.searchParams.get('publish')==='1'){
 if(request.method!=='POST'||!id)return reply({error:'Choose a saved payslip to publish.'},400);
 const task=writes.catch(()=>{}).then(async()=>{const entry=JSON.parse(await readFile(join(root,id+'.json'),'utf8')),agent=entry.snapshot?.cutoff?.agent;if(!/^[A-Za-z0-9_.-]{1,64}$/.test(agent||''))throw Error('Invalid agent');const publishedRoot=join(directory,'published',createHash('sha256').update(agent.toLowerCase()).digest('hex'));await mkdir(publishedRoot,{recursive:true,mode:0o700});const target=join(publishedRoot,id+'.json'),temporary=target+'.'+randomUUID()+'.tmp';await writeFile(temporary,JSON.stringify({...entry,publishedAt:new Date().toISOString(),publishedBy:owner}),{mode:0o600});await rename(temporary,target);return {published:true,agent};});writes=task;return reply(await task);
 }
 if(url.searchParams.get('preferences')==='profile'){

 const profileRoot=join(directory,createHash('sha256').update(owner.toLowerCase()).digest('hex'),'preferences'),path=join(profileRoot,'profile.json');
 if(request.method==='GET'){await writes.catch(()=>{});try{return reply({profile:JSON.parse(await readFile(path,'utf8'))});}catch(e){if(e.code==='ENOENT')return reply({profile:null});throw e;}}
 if(request.method==='POST'){const raw=await request.text();if(raw.length>2000)return reply({error:'Profile is too large.'},413);const data=JSON.parse(raw);if(typeof data?.appName!=='string'||data.appName.trim().length<1||data.appName.trim().length>80)return reply({error:'Enter an app name of 1–80 characters.'},400);const profile={appName:data.appName.trim()};const task=writes.catch(()=>{}).then(async()=>{await mkdir(profileRoot,{recursive:true,mode:0o700});const temp=path+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(profile),{mode:0o600});await rename(temp,path);});writes=task;await task;return reply({profile});}return reply({error:'Method not allowed.'},405);
 }
 if(url.searchParams.get('preferences')==='layout'){
 const layoutRoot=join(directory,createHash('sha256').update(owner.toLowerCase()).digest('hex'),'preferences'),path=join(layoutRoot,'payroll-layout.json');
 if(request.method==='GET'){await writes.catch(()=>{});try{return reply({layout:JSON.parse(await readFile(path,'utf8'))});}catch(e){if(e.code==='ENOENT')return reply({layout:null});throw e;}}
 if(request.method==='POST'){const raw=await request.text();if(raw.length>10000)return reply({error:'Layout is too large.'},413);const data=JSON.parse(raw),order=data?.order,overrides=data?.overrides;if(!Array.isArray(order)||order.length!==22||new Set(order).size!==22||!order.every(i=>Number.isInteger(i)&&i>=0&&i<22)||!overrides||typeof overrides!=='object'||Array.isArray(overrides)||Object.entries(overrides).some(([k,v])=>!/^([0-9]|1[0-9]|2[01])$/.test(k)||typeof v!=='boolean'||([0,15,21].includes(Number(k))&&!v))||!['professional','breakdown'].includes(data.view)||typeof data.hideZero!=='boolean')return reply({error:'Invalid payroll layout.'},400);const layout={order,overrides,view:data.view,hideZero:data.hideZero};const task=writes.catch(()=>{}).then(async()=>{await mkdir(layoutRoot,{recursive:true,mode:0o700});const temporary=path+'.'+randomUUID()+'.tmp';await writeFile(temporary,JSON.stringify(layout),{mode:0o600});await rename(temporary,path);});writes=task;await task;return reply({layout});}return reply({error:'Method not allowed.'},405);
 }
 async function load(){return JSON.parse(await readFile(join(root,id+'.json'),'utf8'));}
 if(request.method==='POST'){const raw=await request.text();if(raw.length>8000000)return reply({error:'Payslip is too large.'},413);const snapshot=JSON.parse(raw);if(!snapshot||!snapshot.cutoff||!Array.isArray(snapshot.cutoff.days)||snapshot.cutoff.days.length>31||!['USD','PHP'].includes(snapshot.currency))return reply({error:'Invalid payslip.'},400);const entry={id:randomUUID(),createdAt:new Date().toISOString(),snapshot};const task=writes.catch(()=>{}).then(async()=>{await mkdir(root,{recursive:true,mode:0o700});await writeFile(join(root,entry.id+'.json'),JSON.stringify(entry),{mode:0o600,flag:'wx'});});writes=task;await task;return reply(entry,201);}
 await writes.catch(()=>{});if(request.method==='GET'){if(id)return reply(await load());let names;try{names=await readdir(root);}catch(e){if(e.code==='ENOENT')names=[];else throw e;}const entries=[];for(const name of names.filter(n=>n.endsWith('.json'))){const e=JSON.parse(await readFile(join(root,name),'utf8'));entries.push({id:e.id,createdAt:e.createdAt,agent:e.snapshot.cutoff.agent,name:e.snapshot.cutoff.name,start:e.snapshot.cutoff.start,end:e.snapshot.cutoff.end,currency:e.snapshot.currency});}return reply({entries:entries.sort((a,b)=>b.createdAt.localeCompare(a.createdAt))});}
 if(request.method==='DELETE'&&id){const entry=await load();const task=writes.catch(()=>{}).then(async()=>{await mkdir(join(root,'deleted'),{recursive:true,mode:0o700});await rename(join(root,id+'.json'),join(root,'deleted',id+'.json'));const agent=entry.snapshot.cutoff.agent;if(/^[A-Za-z0-9_.-]{1,64}$/.test(agent||'')){const published=join(directory,'published',createHash('sha256').update(agent.toLowerCase()).digest('hex'));try{await mkdir(join(published,'deleted'),{recursive:true,mode:0o700});await rename(join(published,id+'.json'),join(published,'deleted',id+'.json'));}catch(e){if(e.code!=='ENOENT')throw e;}}});writes=task;await task;return reply({deleted:true});}return reply({error:'Method not allowed.'},405);
 }catch(e){return reply({error:e.code==='ENOENT'?'Payslip not found.':'Payslip storage is unavailable.'},e.code==='ENOENT'?404:503);}};
}
