import {spiffDailyRows} from './spiff-utils.mjs';
import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {calculateSpiffWeek,spiffBalance,spiffWeek,validateSpiffRule} from './spiff-utils.mjs';import {createSpiffService} from './spiff-storage.mjs';
const rule={id:'rule',date:'2026-10-09',group:'new',category:'transfer',name:'Trainee',scope:'day',cutoff:'13:00',threshold:7,base:200,bonusStep:1,bonusAmount:50,bonusScope:'counted',award:'all',otherBase:0,tiers:[],winner:''};
const records=n=>Array.from({length:n},(_,i)=>({lead:String(i),audio:'/recording'+i,time:'14:'+String(i).padStart(2,'0'),status:'XFER',notes:'[QA: valid]'}));
const members=[{username:'example',group:'new'}],calc=(r,rs)=>calculateSpiffWeek('2026-10-05',members,[r],[{username:'example',date:r.date,recordings:rs}]);
assert.equal(calc(rule,records(7)).rows[0].earned,200);assert.equal(calc(rule,records(8)).rows[0].earned,250);assert.equal(calc({...rule,threshold:12,base:250,bonusStep:2},records(13)).rows[0].earned,250);assert.equal(calc({...rule,threshold:12,base:250,bonusStep:2},records(14)).rows[0].earned,300);
assert.equal(calc({...rule,category:'jollibee',scope:'before',threshold:5,base:150,bonusAmount:0,tiers:[{target:7,amount:250}]},records(7).map(r=>({...r,time:'12:00'}))).rows[0].earned,250);
assert.equal(calc(rule,[...records(7),{...records(1)[0],lead:'bad',notes:'[QA: invalid]'}]).rows[0].earned,200);
assert.equal(calc({...rule,bonusScope:'postLunchAbove'},records(9).map((r,i)=>({...r,time:i<8?'12:'+String(i).padStart(2,'0'):'14:00'}))).rows[0].earned,250);
assert.throws(()=>validateSpiffRule({...rule,scope:'before',cutoff:''}),/cutoff/);assert.throws(()=>spiffWeek('2026-10-06'),/Monday/);
const first={...rule,threshold:1,award:'first',base:250,bonusAmount:0,otherBase:100};const snapshots=['example','other'].map(username=>({username,date:rule.date,recordings:records(1)}));assert.throws(()=>calculateSpiffWeek('2026-10-05',[...members,{username:'other',group:'new'}],[first],snapshots),/tie/);const ranked=calculateSpiffWeek('2026-10-05',[...members,{username:'other',group:'new'}],[{...first,winner:'example'}],snapshots);assert.deepEqual(ranked.rows.map(r=>r.earned),[250,100]);
const dir=await mkdtemp(join(tmpdir(),'qa-spiff-'));try{const service=createSpiffService(dir),send=(actor,data)=>service(new Request('http://spiffs/',{method:data?'POST':'GET',headers:{'X-Reviewer':actor,'X-Spiff-Admin':'owner'},body:data?JSON.stringify(data):undefined}));assert.equal((await send('outsider')).status,403);assert.equal((await send('owner',{action:'access',users:['selected']})).status,200);assert.equal((await send('selected')).status,200);assert.equal((await send('selected',{action:'access',users:['outsider']})).status,400);await send('owner',{action:'rule',rule});const snapshot=calc(rule,records(8));let response=await send('selected',{action:'snapshot',snapshot}),state=await response.json(),week=state.weeks[0];assert.equal(week.rows[0].earned,250);assert.equal((await send('owner',{action:'snapshot',snapshot:structuredClone(snapshot)})).status,200);await send('owner',{action:'rule',rule:{...rule,base:999}});state=await (await send('owner')).json();assert.equal(state.weeks[0].rows[0].earned,250);assert.equal((await send('selected',{action:'eligibility',week:week.id,username:'example',eligibility:'review',reason:'Unauthorized absence needs review'})).status,200);assert.equal((await send('selected',{action:'payment',week:week.id,username:'example',amount:50,date:'2026-10-10',reference:'Cash'})).status,400);await send('owner',{action:'eligibility',week:week.id,username:'example',eligibility:'eligible',reason:'Approved after review'});await send('selected',{action:'payment',week:week.id,username:'example',amount:50,date:'2026-10-10',reference:'Cash'});state=await (await send('owner')).json();assert.equal(spiffBalance(state.weeks[0].rows[0]).status,'Partially paid');assert.equal(state.weeks[0].rows[0].payments[0].recordedBy,'selected');assert.equal((await send('owner',{action:'snapshot',snapshot})).status,400);assert.ok(state.audit.some(event=>event.type==='recalculate'&&event.before.rows[0].earned===250));assert.equal((await send('selected',{action:'payment',week:week.id,username:'example',amount:999,date:'2026-10-10',reference:'Cash'})).status,400);assert.ok(state.audit.length>=6);}finally{await rm(dir,{recursive:true,force:true});}
console.log('PASS: PHP thresholds, replacement tiers, per-pair floor, valid-only records, Eastern wall-clock cutoffs, post-lunch bonuses, first-agent tie review, shared access, frozen snapshots, eligibility and audited partial payments.');

const groupDir=await mkdtemp(join(tmpdir(),'qa-spiff-groups-'));try{const service=createSpiffService(groupDir),send=(actor,data)=>service(new Request('http://spiffs/',{method:data?'POST':'GET',headers:{'X-Reviewer':actor,'X-Spiff-Admin':'owner'},body:data?JSON.stringify(data):undefined}));await send('owner',{action:'access',users:['selected']});assert.equal((await send('outsider',{action:'agentGroups',agents:[{username:'Agent',name:'Name',group:'new'}]})).status,403);await send('selected',{action:'agentGroups',agents:[{username:'Agent',name:'Example Agent',group:'experienced'}]});const restored=createSpiffService(groupDir);let state=await (await restored(new Request('http://spiffs/',{headers:{'X-Reviewer':'owner','X-Spiff-Admin':'owner'}}))).json();assert.equal(state.agentGroups[0].group,'experienced');assert.equal(state.audit.at(-1).actor,'selected');await send('owner',{action:'agentGroups',agents:[{username:'agent',name:'Example Agent',group:'new'}]});state=await (await send('owner')).json();assert.equal(state.agentGroups.length,1);assert.equal(state.agentGroups[0].group,'new');assert.equal((await send('owner',{action:'agentGroups',agents:[{username:'agent',name:'Name',group:'invalid'}]})).status,400);}finally{await rm(groupDir,{recursive:true,force:true});}
const dailyWeek={monday:'2026-10-05',end:'2026-10-10',rows:[{username:'agent',group:'experienced',eligibility:'eligible',days:[{date:'2026-10-09',category:'jollibee',validCount:5,amount:150},{date:'2026-10-09',category:'transfer',validCount:14,amount:400},{date:'2026-10-08',category:'transfer',validCount:20,amount:700}]},{username:'pending',group:'new',eligibility:'review',days:[{date:'2026-10-09',category:'transfer',validCount:10,amount:200}]},{username:'disqualified',group:'new',eligibility:'disqualified',days:[{date:'2026-10-09',category:'transfer',validCount:10,amount:200}]}]};const daily=spiffDailyRows([dailyWeek],'2026-10-09',[{username:'AGENT',name:'Example Agent',group:'new'}]);assert.equal(daily[0].earned,550);assert.equal(daily[0].name,'Example Agent');assert.equal(daily[0].group,'experienced');assert.equal(daily[0].lunchCount,5);assert.equal(daily[0].transferCount,14);assert.equal(daily[1].payable,null);assert.equal(daily[2].payable,0);assert.deepEqual(spiffDailyRows([dailyWeek],'2026-10-11'),[]);console.log('PASS: shared saved agent groups, case-insensitive updates, restart persistence and audit; daily category totals, scoped counts, historical groups and eligibility.');

const partialDir=await mkdtemp(join(tmpdir(),'qa-spiff-partial-'));try{const service=createSpiffService(partialDir),send=snapshot=>service(new Request('http://spiffs/',{method:'POST',headers:{'X-Reviewer':'owner','X-Spiff-Admin':'owner'},body:JSON.stringify({action:'snapshot',snapshot})}));const initial=calculateSpiffWeek('2026-10-05',[...members,{username:'other',group:'new'}],[rule],[{username:'example',date:rule.date,recordings:records(8)},{username:'other',date:rule.date,recordings:records(8)}]);let state=await (await send(initial)).json();const untouched=structuredClone(state.weeks[0].rows.find(r=>r.username==='other'));const updated=calc({...rule,base:300},records(8));state=await (await send(updated)).json();assert.equal(state.weeks[0].rows.length,2);const retained=state.weeks[0].rows.find(r=>r.username==='other');assert.equal(retained.earned,untouched.earned);assert.deepEqual(retained.days,untouched.days);assert.equal(retained.calculationRules[0].base,rule.base);assert.equal(state.weeks[0].rows.find(r=>r.username==='example').earned,350);assert.ok(state.audit.some(e=>e.type==='recalculate'&&e.before.rows.length===2));const competition=structuredClone(updated);competition.rules=[first];assert.equal((await send(competition)).status,400);}finally{await rm(partialDir,{recursive:true,force:true});}console.log('PASS: selected-agent recalculation retains other earnings and original rules, audits revisions, and rejects incomplete first-qualifier competitions.');
