import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {calculateSpiffWeek,spiffBalance,spiffWeek,validateSpiffRule} from './spiff-utils.mjs';import {createSpiffService} from './spiff-storage.mjs';
const rule={id:'rule',date:'2026-10-09',group:'new',category:'transfer',name:'Trainee',scope:'day',cutoff:'13:00',threshold:7,base:200,bonusStep:1,bonusAmount:50,bonusScope:'counted',award:'all',otherBase:0,tiers:[],winner:''};
const records=n=>Array.from({length:n},(_,i)=>({lead:String(i),audio:'/recording'+i,time:'14:'+String(i).padStart(2,'0'),status:'XFER',notes:'[QA: valid]'}));
const members=[{username:'example',group:'new'}],calc=(r,rs)=>calculateSpiffWeek('2026-10-05',members,[r],[{username:'example',date:r.date,recordings:rs}]);
assert.equal(calc(rule,records(7)).rows[0].earned,200);assert.equal(calc(rule,records(8)).rows[0].earned,250);assert.equal(calc({...rule,threshold:12,base:250,bonusStep:2},records(13)).rows[0].earned,250);assert.equal(calc({...rule,threshold:12,base:250,bonusStep:2},records(14)).rows[0].earned,300);
assert.equal(calc({...rule,category:'jollibee',scope:'before',threshold:5,base:150,bonusAmount:0,tiers:[{target:7,amount:250}]},records(7).map(r=>({...r,time:'12:00'}))).rows[0].earned,250);
assert.equal(calc(rule,[...records(7),{...records(1)[0],lead:'bad',notes:'[QA: invalid]'}]).rows[0].earned,200);
assert.equal(calc({...rule,bonusScope:'postLunchAbove'},records(9).map((r,i)=>({...r,time:i<8?'12:'+String(i).padStart(2,'0'):'14:00'}))).rows[0].earned,250);
assert.throws(()=>validateSpiffRule({...rule,scope:'before',cutoff:''}),/cutoff/);assert.throws(()=>spiffWeek('2026-10-06'),/Monday/);
const first={...rule,threshold:1,award:'first',base:250,bonusAmount:0,otherBase:100};const snapshots=['example','other'].map(username=>({username,date:rule.date,recordings:records(1)}));assert.throws(()=>calculateSpiffWeek('2026-10-05',[...members,{username:'other',group:'new'}],[first],snapshots),/tie/);const ranked=calculateSpiffWeek('2026-10-05',[...members,{username:'other',group:'new'}],[{...first,winner:'example'}],snapshots);assert.deepEqual(ranked.rows.map(r=>r.earned),[250,100]);
const dir=await mkdtemp(join(tmpdir(),'qa-spiff-'));try{const service=createSpiffService(dir),send=(actor,data)=>service(new Request('http://spiffs/',{method:data?'POST':'GET',headers:{'X-Reviewer':actor,'X-Spiff-Admin':'owner'},body:data?JSON.stringify(data):undefined}));assert.equal((await send('outsider')).status,403);assert.equal((await send('owner',{action:'access',users:['selected']})).status,200);assert.equal((await send('selected')).status,200);assert.equal((await send('selected',{action:'access',users:['outsider']})).status,400);await send('owner',{action:'rule',rule});const snapshot=calc(rule,records(8));let response=await send('selected',{action:'snapshot',snapshot}),state=await response.json(),week=state.weeks[0];assert.equal(week.rows[0].earned,250);assert.equal((await send('owner',{action:'snapshot',snapshot:structuredClone(snapshot)})).status,200);await send('owner',{action:'rule',rule:{...rule,base:999}});state=await (await send('owner')).json();assert.equal(state.weeks[0].rows[0].earned,250);assert.equal((await send('selected',{action:'eligibility',week:week.id,username:'example',eligibility:'review',reason:'Unauthorized absence needs review'})).status,200);assert.equal((await send('selected',{action:'payment',week:week.id,username:'example',amount:50,date:'2026-10-10',reference:'Cash'})).status,400);await send('owner',{action:'eligibility',week:week.id,username:'example',eligibility:'eligible',reason:'Approved after review'});await send('selected',{action:'payment',week:week.id,username:'example',amount:50,date:'2026-10-10',reference:'Cash'});state=await (await send('owner')).json();assert.equal(spiffBalance(state.weeks[0].rows[0]).status,'Partially paid');assert.equal(state.weeks[0].rows[0].payments[0].recordedBy,'selected');assert.equal((await send('owner',{action:'snapshot',snapshot})).status,400);assert.ok(state.audit.some(event=>event.type==='recalculate'&&event.before.rows[0].earned===250));assert.equal((await send('selected',{action:'payment',week:week.id,username:'example',amount:999,date:'2026-10-10',reference:'Cash'})).status,400);assert.ok(state.audit.length>=6);}finally{await rm(dir,{recursive:true,force:true});}
console.log('PASS: PHP thresholds, replacement tiers, per-pair floor, valid-only records, Eastern wall-clock cutoffs, post-lunch bonuses, first-agent tie review, shared access, frozen snapshots, eligibility and audited partial payments.');
