let spiffState=null,spiffRequest=null,spiffGeneration=0,spiffRulesDate=null;
const spiffPage=/\/spiffs\/?$/.test(location.pathname);
$('open-spiffs').href=viewerBase+'spiffs';
if(spiffPage){$('open-spiffs').setAttribute('aria-current','page');$('nav-recordings').removeAttribute('aria-current');}
function spiffMessage(text){$('spiff-status').textContent=text;}
async function spiffFetch(data){const response=await fetch('/api/spiffs',data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);const result=await response.json();if(!response.ok)throw Error(result.error||'Spiff request failed.');return result;}
async function loadSpiffs(){const generation=++spiffGeneration;try{const state=await spiffFetch();if(!authorization||generation!==spiffGeneration)return;spiffState=state;renderSpiffs();spiffMessage('Rules and weekly payments loaded.');}catch(error){if(authorization&&generation===spiffGeneration)spiffMessage(error.message);}}
function spiffButton(text,action){const button=document.createElement('button');button.type='button';button.textContent=text;button.onclick=action;return button;}
function renderSpiffs(){renderSpiffDailyReport();$('spiff-access-panel').hidden=!spiffState.admin;$('spiff-access').value=spiffState.access.join(', ');renderSpiffRuleCalendar();const rules=$('spiff-rules');rules.replaceChildren();for(const rule of spiffState.rules.filter(rule=>rule.date===spiffRulesDate).sort((a,b)=>a.group.localeCompare(b.group)||a.category.localeCompare(b.category))){const row=document.createElement('tr');for(const value of [rule.date,rule.group,rule.category,rule.name,rule.scope+(rule.cutoff?' · '+rule.cutoff+' ET':''),rule.threshold,'₱'+rule.base,'₱'+rule.bonusAmount+' / '+rule.bonusStep+' extra',rule.award==='first'?'First qualifier; others ₱'+rule.otherBase:'Everyone']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}const actions=document.createElement('td');actions.append(spiffButton('Edit',()=>{for(const key of ['date','group','category','name','scope','cutoff','threshold','base','bonusStep','bonusAmount','bonusScope','award','otherBase','winner'])$('spiff-rule-'+key).value=rule[key]??'';$('spiff-rule-tiers').value=rule.tiers.map(t=>t.target+':'+t.amount).join(', ');$('spiff-rule-name').focus();}));row.append(actions);rules.append(row);}
const host=$('spiff-weeks');host.replaceChildren();for(const week of [...spiffState.weeks].sort((a,b)=>b.monday.localeCompare(a.monday))){const section=document.createElement('section');section.className='spiff-week';const heading=document.createElement('h2');heading.textContent=week.monday+' – '+week.end+' · PHP';section.append(heading);const table=document.createElement('table'),head=document.createElement('tr');for(const value of ['Agent','Group','Earned','Eligibility','Paid','Balance','Status','Actions']){const th=document.createElement('th');th.textContent=value;head.append(th);}table.append(head);for(const agent of week.rows){const balance=spiffBalance(agent),row=document.createElement('tr');for(const value of [agent.username,agent.group,'₱'+agent.earned,agent.eligibility,'₱'+balance.paid,'₱'+balance.balance,balance.status]){const td=document.createElement('td');td.textContent=value;row.append(td);}const actions=document.createElement('td');actions.append(spiffButton('Details',()=>showSpiffDetails(week,agent)),spiffButton('Eligibility',()=>openSpiffAction(week,agent,'eligibility')),spiffButton('Record payment',()=>openSpiffAction(week,agent,'payment')));row.append(actions);table.append(row);}const wrap=document.createElement('div');wrap.className='table-wrap';wrap.append(table);section.append(wrap);host.append(section);}}
function showSpiffDetails(week,agent){const host=$('spiff-details');host.replaceChildren();const heading=document.createElement('h3');heading.textContent=agent.username+' · '+week.monday;host.append(heading);for(const day of agent.days){const p=document.createElement('p');p.textContent=day.date+' · '+day.name+' · '+day.validCount+' valid transfers · base ₱'+day.base+' + bonus ₱'+day.bonus+' = ₱'+day.amount;host.append(p);}for(const payment of agent.payments){const p=document.createElement('p');p.textContent=payment.date+' · Paid ₱'+payment.amount+' · '+payment.reference+' · Recorded by '+payment.recordedBy;host.append(p);}for(const event of spiffState.audit.filter(e=>e.week===week.id&&(!e.username||e.username===agent.username))){const p=document.createElement('p');p.textContent=event.at+' · '+event.type+' · '+event.actor+(event.after?.reason?' · '+event.after.reason:'');host.append(p);}const reason=document.createElement('p');reason.textContent='Eligibility: '+agent.eligibility+(agent.reason?' · '+agent.reason:'');host.append(reason);$('spiff-details-dialog').showModal();}
function openSpiffAction(week,agent,action){$('spiff-action-week').value=week.id;$('spiff-action-agent').value=agent.username;$('spiff-action-type').value=action;$('spiff-action-title').textContent=(action==='payment'?'Record payment':'Update eligibility')+' · '+agent.username;$('spiff-payment-fields').hidden=action!=='payment';$('spiff-eligibility-fields').hidden=action!=='eligibility';$('spiff-action-amount').value=spiffBalance(agent).balance;$('spiff-action-date').value=spiffEasternDate();$('spiff-action-reference').value='';$('spiff-action-reason').value=agent.reason;$('spiff-action-eligibility').value=agent.eligibility;$('spiff-action-status').textContent='';$('spiff-action-dialog').showModal();}
async function spiffSave(data){if(spiffRequest)throw Error('A spiff request is already running.');const generation=spiffGeneration;spiffRequest=true;for(const button of $('spiffs-page').querySelectorAll('button'))button.disabled=true;try{let state=await spiffFetch(data);if(state.job){const id=state.job;while(authorization&&generation===spiffGeneration){await new Promise(resolve=>setTimeout(resolve,2000));const response=await fetch('/api/spiffs?'+new URLSearchParams({job:id})),job=await response.json();if(!response.ok)throw Error(job.error||'Calculation status unavailable.');if(job.status==='failed')throw Error(job.error);if(job.status==='done'){state=job.result;break;}spiffMessage(job.progress||'Calculating…');}}if(!authorization||generation!==spiffGeneration)return;spiffState=state;renderSpiffs();spiffMessage('Saved.');}finally{spiffRequest=false;for(const button of $('spiffs-page').querySelectorAll('button'))button.disabled=false;}}
$('spiff-rule-form').onsubmit=async event=>{event.preventDefault();try{const rule={};for(const key of ['date','group','category','name','scope','cutoff','bonusScope','award','winner'])rule[key]=$('spiff-rule-'+key).value;for(const key of ['threshold','base','bonusStep','bonusAmount','otherBase'])rule[key]=Number($('spiff-rule-'+key).value);const tierText=$('spiff-rule-tiers').value.trim();rule.tiers=tierText?tierText.split(',').map(value=>{const [target,amount]=value.trim().split(':');return {target:Number(target),amount:Number(amount)};}):[];validateSpiffRule(rule);spiffRulesDate=rule.date;await spiffSave({action:'rule',rule});}catch(error){spiffMessage(error.message);}};
$('spiff-week-form').onsubmit=async event=>{event.preventDefault();try{const members=spiffSelectedMembers();spiffWeek($('spiff-monday').value);if(!members.length)throw Error('Enter agents and their groups.');spiffMessage('Fetching valid XFER recordings and calculating. Keep this page open.');await spiffFetch({action:'agentGroups',agents:members.map(m=>({...m,name:spiffAgentCatalog.find(a=>a.username.toLowerCase()===m.username.toLowerCase())?.name||m.username}))});await spiffSave({action:'generate',monday:$('spiff-monday').value,members});}catch(error){spiffMessage(error.message);}};
$('spiff-action-form').onsubmit=async event=>{event.preventDefault();const action=$('spiff-action-type').value,data={action,week:$('spiff-action-week').value,username:$('spiff-action-agent').value};if(action==='payment')Object.assign(data,{amount:Number($('spiff-action-amount').value),date:$('spiff-action-date').value,reference:$('spiff-action-reference').value});else Object.assign(data,{eligibility:$('spiff-action-eligibility').value,reason:$('spiff-action-reason').value});$('spiff-action-save').disabled=true;try{await spiffSave(data);$('spiff-action-dialog').close();}catch(error){$('spiff-action-status').textContent=error.message;}finally{$('spiff-action-save').disabled=false;}};
$('spiff-action-close').onclick=()=>$('spiff-action-dialog').close();$('spiff-details-close').onclick=()=>$('spiff-details-dialog').close();$('spiff-refresh').onclick=loadSpiffs;
$('spiff-access-save').onclick=async()=>{try{await spiffSave({action:'access',users:$('spiff-access').value.split(',').map(u=>u.trim()).filter(Boolean)});}catch(error){spiffMessage(error.message);}};
// Rule dates and recording clock values are Eastern wall time; never convert them through the viewer's timezone.
$('spiff-rule-date').value=spiffEasternDate();
const spiffToday=$('spiff-rule-date').value,spiffDay=new Date(spiffToday+'T00:00:00Z').getUTCDay();$('spiff-monday').value=new Date(Date.parse(spiffToday)-((spiffDay+6)%7)*86400000).toISOString().slice(0,10);

$('spiff-supervisors-load').onclick=async()=>{try{const response=await fetch('/api/spiffs?directory=1'),data=await response.json();if(!response.ok)throw Error(data.error);if(!authorization)return;const host=$('spiff-supervisors-list');host.replaceChildren();for(const user of data.users){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=user.username;input.checked=spiffState.access.includes(user.username.toLowerCase());label.append(input,document.createTextNode(user.name+' ('+user.username+')'));host.append(label);input.onchange=()=>{$('spiff-access').value=[...host.querySelectorAll('input:checked')].map(i=>i.value).join(', ');};}spiffMessage('Choose supervisors. Level 7–9 is verified when you save access.');}catch(error){spiffMessage(error.message);}};
function spiffEasternDate(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=type=>parts.find(part=>part.type===type).value;return value('year')+'-'+value('month')+'-'+value('day');}

let spiffAgentCatalog=[],spiffAgentLoading=false;
function spiffSelectedMembers(){return $('spiff-members').value.split('\n').filter(line=>line.trim()).map(line=>{const parts=line.split(',').map(value=>value.trim());if(parts.length!==2||!/^[A-Za-z0-9_.-]{1,64}$/.test(parts[0])||!['new','experienced'].includes(parts[1]))throw Error('Choose New or Experienced for every selected agent. Manual entries use username,new or username,experienced.');return {username:parts[0],group:parts[1]};});}
function spiffAgentProfile(username){const profile=spiffState?.agentGroups?.find(p=>p.username.toLowerCase()===username.toLowerCase());if(profile)return profile;for(const week of [...(spiffState?.weeks||[])].sort((a,b)=>b.createdAt.localeCompare(a.createdAt))){const row=week.rows.find(r=>r.username.toLowerCase()===username.toLowerCase());if(row)return row;}return null;}
function spiffUpdateMembers(){const host=$('spiff-agents-list');$('spiff-members').value=[...host.querySelectorAll('input:checked')].map(input=>input.value+','+input.closest('.spiff-agent-row').querySelector('select').value).join('\n');spiffFilterAgents();}
function spiffFilterAgents(){const query=$('spiff-agent-search').value.trim().toLowerCase(),rows=[...$('spiff-agents-list').children];let visible=0,selected=0;for(const row of rows){row.hidden=!row.dataset.search.includes(query);if(!row.hidden)visible++;if(row.querySelector('input').checked)selected++;}$('spiff-agent-count').textContent=selected+' selected · '+visible+' of '+rows.length+' agents · Groups saved for future calculations';}
function renderSpiffAgents(){const host=$('spiff-agents-list');let selected=[];try{selected=spiffSelectedMembers();}catch{}host.replaceChildren();for(const agent of spiffAgentCatalog){const member=selected.find(m=>m.username.toLowerCase()===agent.username.toLowerCase()),profile=spiffAgentProfile(agent.username),row=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input'),name=document.createElement('span'),title=document.createElement('strong'),username=document.createElement('small'),select=document.createElement('select');row.className='spiff-agent-row';row.dataset.search=(agent.name+' '+agent.username).toLowerCase();input.type='checkbox';input.value=agent.username;input.checked=!!member;title.textContent=agent.name;username.textContent=agent.username;name.className='spiff-agent-name';name.append(title,username);label.append(input,name);select.setAttribute('aria-label','Group for '+agent.name);select.append(new Option('Choose group',''),new Option('New / trainee','new'),new Option('Experienced','experienced'));select.value=member?.group||profile?.group||'';input.disabled=!select.value;row.append(label,select);host.append(row);input.onchange=spiffUpdateMembers;select.onchange=async()=>{const previous=spiffAgentProfile(agent.username)?.group||member?.group||'',group=select.value,generation=spiffGeneration;if(!group){input.disabled=true;input.checked=false;spiffUpdateMembers();return;}select.disabled=true;input.disabled=true;try{const state=await spiffFetch({action:'agentGroups',agents:[{username:agent.username,name:agent.name,group}]});if(!authorization||generation!==spiffGeneration)return;spiffState.agentGroups=state.agentGroups;spiffMessage('Saved '+agent.name+' as '+(group==='new'?'New / trainee':'Experienced')+'.');}catch(error){select.value=previous;if(!previous)input.checked=false;spiffMessage(error.message);}finally{select.disabled=false;input.disabled=!select.value;if(authorization&&generation===spiffGeneration)spiffUpdateMembers();}};}spiffFilterAgents();}
$('spiff-agents-load').onclick=async()=>{if(spiffAgentLoading)return;const monday=$('spiff-monday').value,generation=spiffGeneration;spiffAgentLoading=true;$('spiff-agents-load').disabled=true;try{const dates=spiffWeek(monday),agents=new Map();for(const date of dates){const response=await fetch('/api/agents?'+new URLSearchParams({date})),data=await response.json();if(!response.ok)throw Error(data.error);if(!authorization||generation!==spiffGeneration||monday!==$('spiff-monday').value)return;for(const agent of data.agents)agents.set(agent.username.toLowerCase(),agent);}spiffAgentCatalog=[...agents.values()].sort((a,b)=>a.name.localeCompare(b.name));renderSpiffAgents();}catch(error){if(authorization&&generation===spiffGeneration)spiffMessage(error.message);}finally{spiffAgentLoading=false;$('spiff-agents-load').disabled=false;}};
$('spiff-agent-search').oninput=spiffFilterAgents;$('spiff-agents-all').onclick=()=>{for(const row of $('spiff-agents-list').children){const input=row.querySelector('input');if(!row.hidden&&!input.disabled)input.checked=true;}spiffUpdateMembers();};$('spiff-agents-clear').onclick=()=>{for(const input of $('spiff-agents-list').querySelectorAll('input'))input.checked=false;spiffUpdateMembers();};$('spiff-monday').onchange=()=>{spiffAgentCatalog=[];$('spiff-agents-list').replaceChildren();$('spiff-members').value='';$('spiff-agent-count').textContent='Load agents for this week.';};$('spiff-members').oninput=()=>{if(spiffAgentCatalog.length)renderSpiffAgents();};
function spiffDailyReportData(){return spiffDailyRows(spiffState?.weeks||[],$('spiff-report-date').value,spiffState?.agentGroups||[]);}
function renderSpiffDailyReport(){const rows=spiffDailyReportData(),host=$('spiff-daily-report');host.replaceChildren();$('spiff-report-export').disabled=!rows.length;if(!rows.length){$('spiff-report-status').textContent='No saved calculation for this date. Calculate the week first.';return;}const table=document.createElement('table'),head=document.createElement('tr');for(const title of ['Agent','Group','Lunch qualifying','Transfer qualifying','Jollibee','Transfer reward','Earned','Eligibility','Payable']){const th=document.createElement('th');th.textContent=title;head.append(th);}table.append(head);for(const item of rows){const row=document.createElement('tr');for(const value of [item.name,item.group,item.lunchCount??'—',item.transferCount??'—','₱'+item.jollibee,'₱'+item.transfer,'₱'+item.earned,item.eligibility,item.payable===null?'Pending review':'₱'+item.payable]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}table.append(row);}const total=document.createElement('tr');total.className='spiff-total-row';const sum=key=>rows.reduce((n,r)=>n+(r[key]??0),0);for(const value of ['Total','','','','₱'+sum('jollibee'),'₱'+sum('transfer'),'₱'+sum('earned'),'','₱'+sum('payable')]){const td=document.createElement('td');td.textContent=value;total.append(td);}table.append(total);host.append(table);$('spiff-report-status').textContent=rows.length+' agents · '+$('spiff-report-date').value+' ET · Qualifying counts follow each rule’s target scope. Payable excludes pending review and disqualified agents.';}
$('spiff-report-date').value=spiffEasternDate();$('spiff-report-date').onchange=renderSpiffDailyReport;$('spiff-report-export').onclick=()=>{const rows=spiffDailyReportData();if(!rows.length)return;const date=$('spiff-report-date').value,csv=[['Date (ET)','Username','Name','Group','Lunch qualifying','Transfer qualifying','Jollibee (PHP)','Transfer reward (PHP)','Earned (PHP)','Eligibility','Payable (PHP)'],...rows.map(r=>[date,r.username,r.name,r.group,r.lunchCount??'',r.transferCount??'',r.jollibee,r.transfer,r.earned,r.eligibility,r.payable??'Pending review'])].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='spiffs-'+date+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};

function spiffRuleDateMove(days){const date=new Date(spiffRulesDate+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+days);spiffRulesDate=date.toISOString().slice(0,10);$('spiff-rule-date').value=spiffRulesDate;renderSpiffs();}
function renderSpiffRuleCalendar(){spiffRulesDate??=spiffEasternDate();$('spiff-rules-date').value=spiffRulesDate;const date=new Date(spiffRulesDate+'T00:00:00Z');date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));const host=$('spiff-rule-days');host.replaceChildren();for(let i=0;i<7;i++){const day=new Date(date);day.setUTCDate(day.getUTCDate()+i);const value=day.toISOString().slice(0,10),count=spiffState.rules.filter(rule=>rule.date===value).length;const button=spiffButton('',()=>{spiffRulesDate=value;$('spiff-rule-date').value=value;renderSpiffs();});button.className='spiff-rule-day';button.setAttribute('aria-label',value+' · '+count+' rules');button.setAttribute('aria-pressed',String(value===spiffRulesDate));const label=document.createElement('span');label.textContent=day.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'});const badge=document.createElement('small');badge.textContent=count+' '+(count===1?'rule':'rules');button.append(label,badge);host.append(button);}const count=spiffState.rules.filter(rule=>rule.date===spiffRulesDate).length;$('spiff-rules-summary').textContent=spiffRulesDate+' ET · '+(count?count+' saved rules':'No saved rules. Choose this date in the form to add one.');}
$('spiff-rules-prev').onclick=()=>spiffRuleDateMove(-7);
$('spiff-rules-next').onclick=()=>spiffRuleDateMove(7);
$('spiff-rules-today').onclick=()=>{spiffRulesDate=spiffEasternDate();$('spiff-rule-date').value=spiffRulesDate;renderSpiffs();};
$('spiff-rules-date').onchange=()=>{if(!spiffDate($('spiff-rules-date').value))return;spiffRulesDate=$('spiff-rules-date').value;$('spiff-rule-date').value=spiffRulesDate;renderSpiffs();};
