let spiffState=null,spiffRequest=null,spiffGeneration=0;
const spiffPage=/\/spiffs\/?$/.test(location.pathname);
$('open-spiffs').href=viewerBase+'spiffs';
if(spiffPage){$('open-spiffs').setAttribute('aria-current','page');$('nav-recordings').removeAttribute('aria-current');}
function spiffMessage(text){$('spiff-status').textContent=text;}
async function spiffFetch(data){const response=await fetch('/api/spiffs',data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);const result=await response.json();if(!response.ok)throw Error(result.error||'Spiff request failed.');return result;}
async function loadSpiffs(){const generation=++spiffGeneration;try{const state=await spiffFetch();if(!authorization||generation!==spiffGeneration)return;spiffState=state;renderSpiffs();spiffMessage('Rules and weekly payments loaded.');}catch(error){if(authorization&&generation===spiffGeneration)spiffMessage(error.message);}}
function spiffButton(text,action){const button=document.createElement('button');button.type='button';button.textContent=text;button.onclick=action;return button;}
function renderSpiffs(){$('spiff-access-panel').hidden=!spiffState.admin;$('spiff-access').value=spiffState.access.join(', ');const rules=$('spiff-rules');rules.replaceChildren();for(const rule of [...spiffState.rules].sort((a,b)=>b.date.localeCompare(a.date))){const row=document.createElement('tr');for(const value of [rule.date,rule.group,rule.category,rule.name,rule.scope+(rule.cutoff?' · '+rule.cutoff+' ET':''),rule.threshold,'₱'+rule.base,'₱'+rule.bonusAmount+' / '+rule.bonusStep+' extra',rule.award==='first'?'First qualifier; others ₱'+rule.otherBase:'Everyone']){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}const actions=document.createElement('td');actions.append(spiffButton('Edit',()=>{for(const key of ['date','group','category','name','scope','cutoff','threshold','base','bonusStep','bonusAmount','bonusScope','award','otherBase','winner'])$('spiff-rule-'+key).value=rule[key]??'';$('spiff-rule-tiers').value=rule.tiers.map(t=>t.target+':'+t.amount).join(', ');$('spiff-rule-name').focus();}));row.append(actions);rules.append(row);}
const host=$('spiff-weeks');host.replaceChildren();for(const week of [...spiffState.weeks].sort((a,b)=>b.monday.localeCompare(a.monday))){const section=document.createElement('section');section.className='spiff-week';const heading=document.createElement('h2');heading.textContent=week.monday+' – '+week.end+' · PHP';section.append(heading);const table=document.createElement('table'),head=document.createElement('tr');for(const value of ['Agent','Group','Earned','Eligibility','Paid','Balance','Status','Actions']){const th=document.createElement('th');th.textContent=value;head.append(th);}table.append(head);for(const agent of week.rows){const balance=spiffBalance(agent),row=document.createElement('tr');for(const value of [agent.username,agent.group,'₱'+agent.earned,agent.eligibility,'₱'+balance.paid,'₱'+balance.balance,balance.status]){const td=document.createElement('td');td.textContent=value;row.append(td);}const actions=document.createElement('td');actions.append(spiffButton('Details',()=>showSpiffDetails(week,agent)),spiffButton('Eligibility',()=>openSpiffAction(week,agent,'eligibility')),spiffButton('Record payment',()=>openSpiffAction(week,agent,'payment')));row.append(actions);table.append(row);}const wrap=document.createElement('div');wrap.className='table-wrap';wrap.append(table);section.append(wrap);host.append(section);}}
function showSpiffDetails(week,agent){const host=$('spiff-details');host.replaceChildren();const heading=document.createElement('h3');heading.textContent=agent.username+' · '+week.monday;host.append(heading);for(const day of agent.days){const p=document.createElement('p');p.textContent=day.date+' · '+day.name+' · '+day.validCount+' valid transfers · base ₱'+day.base+' + bonus ₱'+day.bonus+' = ₱'+day.amount;host.append(p);}for(const payment of agent.payments){const p=document.createElement('p');p.textContent=payment.date+' · Paid ₱'+payment.amount+' · '+payment.reference+' · Recorded by '+payment.recordedBy;host.append(p);}for(const event of spiffState.audit.filter(e=>e.week===week.id&&(!e.username||e.username===agent.username))){const p=document.createElement('p');p.textContent=event.at+' · '+event.type+' · '+event.actor+(event.after?.reason?' · '+event.after.reason:'');host.append(p);}const reason=document.createElement('p');reason.textContent='Eligibility: '+agent.eligibility+(agent.reason?' · '+agent.reason:'');host.append(reason);$('spiff-details-dialog').showModal();}
function openSpiffAction(week,agent,action){$('spiff-action-week').value=week.id;$('spiff-action-agent').value=agent.username;$('spiff-action-type').value=action;$('spiff-action-title').textContent=(action==='payment'?'Record payment':'Update eligibility')+' · '+agent.username;$('spiff-payment-fields').hidden=action!=='payment';$('spiff-eligibility-fields').hidden=action!=='eligibility';$('spiff-action-amount').value=spiffBalance(agent).balance;$('spiff-action-date').value=spiffEasternDate();$('spiff-action-reference').value='';$('spiff-action-reason').value=agent.reason;$('spiff-action-eligibility').value=agent.eligibility;$('spiff-action-status').textContent='';$('spiff-action-dialog').showModal();}
async function spiffSave(data){if(spiffRequest)throw Error('A spiff request is already running.');const generation=spiffGeneration;spiffRequest=true;for(const button of $('spiffs-page').querySelectorAll('button'))button.disabled=true;try{let state=await spiffFetch(data);if(state.job){const id=state.job;while(authorization&&generation===spiffGeneration){await new Promise(resolve=>setTimeout(resolve,2000));const response=await fetch('/api/spiffs?'+new URLSearchParams({job:id})),job=await response.json();if(!response.ok)throw Error(job.error||'Calculation status unavailable.');if(job.status==='failed')throw Error(job.error);if(job.status==='done'){state=job.result;break;}spiffMessage(job.progress||'Calculating…');}}if(!authorization||generation!==spiffGeneration)return;spiffState=state;renderSpiffs();spiffMessage('Saved.');}finally{spiffRequest=false;for(const button of $('spiffs-page').querySelectorAll('button'))button.disabled=false;}}
$('spiff-rule-form').onsubmit=async event=>{event.preventDefault();try{const rule={};for(const key of ['date','group','category','name','scope','cutoff','bonusScope','award','winner'])rule[key]=$('spiff-rule-'+key).value;for(const key of ['threshold','base','bonusStep','bonusAmount','otherBase'])rule[key]=Number($('spiff-rule-'+key).value);const tierText=$('spiff-rule-tiers').value.trim();rule.tiers=tierText?tierText.split(',').map(value=>{const [target,amount]=value.trim().split(':');return {target:Number(target),amount:Number(amount)};}):[];validateSpiffRule(rule);await spiffSave({action:'rule',rule});}catch(error){spiffMessage(error.message);}};
$('spiff-week-form').onsubmit=async event=>{event.preventDefault();try{const members=$('spiff-members').value.split('\n').filter(line=>line.trim()).map(line=>{const [username,group]=line.split(',').map(v=>v.trim());return {username,group};});spiffWeek($('spiff-monday').value);if(!members.length)throw Error('Enter agents and their groups.');spiffMessage('Fetching valid XFER recordings and calculating. Keep this page open.');await spiffSave({action:'generate',monday:$('spiff-monday').value,members});}catch(error){spiffMessage(error.message);}};
$('spiff-action-form').onsubmit=async event=>{event.preventDefault();const action=$('spiff-action-type').value,data={action,week:$('spiff-action-week').value,username:$('spiff-action-agent').value};if(action==='payment')Object.assign(data,{amount:Number($('spiff-action-amount').value),date:$('spiff-action-date').value,reference:$('spiff-action-reference').value});else Object.assign(data,{eligibility:$('spiff-action-eligibility').value,reason:$('spiff-action-reason').value});$('spiff-action-save').disabled=true;try{await spiffSave(data);$('spiff-action-dialog').close();}catch(error){$('spiff-action-status').textContent=error.message;}finally{$('spiff-action-save').disabled=false;}};
$('spiff-action-close').onclick=()=>$('spiff-action-dialog').close();$('spiff-details-close').onclick=()=>$('spiff-details-dialog').close();$('spiff-refresh').onclick=loadSpiffs;
$('spiff-access-save').onclick=async()=>{try{await spiffSave({action:'access',users:$('spiff-access').value.split(',').map(u=>u.trim()).filter(Boolean)});}catch(error){spiffMessage(error.message);}};
// Rule dates and recording clock values are Eastern wall time; never convert them through the viewer's timezone.
$('spiff-rule-date').value=spiffEasternDate();
const spiffToday=$('spiff-rule-date').value,spiffDay=new Date(spiffToday+'T00:00:00Z').getUTCDay();$('spiff-monday').value=new Date(Date.parse(spiffToday)-((spiffDay+6)%7)*86400000).toISOString().slice(0,10);

$('spiff-supervisors-load').onclick=async()=>{try{const response=await fetch('/api/spiffs?directory=1'),data=await response.json();if(!response.ok)throw Error(data.error);if(!authorization)return;const host=$('spiff-supervisors-list');host.replaceChildren();for(const user of data.users){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=user.username;input.checked=spiffState.access.includes(user.username.toLowerCase());label.append(input,document.createTextNode(user.name+' ('+user.username+')'));host.append(label);input.onchange=()=>{$('spiff-access').value=[...host.querySelectorAll('input:checked')].map(i=>i.value).join(', ');};}spiffMessage('Choose supervisors. Level 7–9 is verified when you save access.');}catch(error){spiffMessage(error.message);}};
$('spiff-agents-load').onclick=async()=>{try{const dates=spiffWeek($('spiff-monday').value),agents=new Map();for(const date of dates){const response=await fetch('/api/agents?'+new URLSearchParams({date})),data=await response.json();if(!response.ok)throw Error(data.error);if(!authorization)return;for(const agent of data.agents)agents.set(agent.username,agent);}const host=$('spiff-agents-list');host.replaceChildren();const update=()=>{$('spiff-members').value=[...host.querySelectorAll('input:checked')].map(input=>input.value+','+input.parentElement.querySelector('select').value).join('\n');};for(const agent of [...agents.values()].sort((a,b)=>a.name.localeCompare(b.name))){const label=document.createElement('label'),input=document.createElement('input'),select=document.createElement('select');input.type='checkbox';input.value=agent.username;select.append(new Option('New / trainee','new'),new Option('Experienced','experienced'));label.append(input,document.createTextNode(agent.name+' ('+agent.username+')'),select);host.append(label);input.onchange=update;select.onchange=update;}}catch(error){spiffMessage(error.message);}};

function spiffEasternDate(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const value=type=>parts.find(part=>part.type===type).value;return value('year')+'-'+value('month')+'-'+value('day');}
