import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
// Exercise the actual built Worker with mocked outbound fetch; no workerd process required.
class Miniflare{constructor(options){const context=vm.createContext({Response,Request,Headers,URL,URLSearchParams,TextEncoder,TextDecoder,AbortSignal,crypto,btoa,atob,fetch:options.outboundService?((url,init)=>options.outboundService(new Request(url,init))):fetch});vm.runInContext(readFileSync('dist/server/index.js','utf8').replace('export default {','globalThis.worker={'),context);this.worker=context.worker;this.env=options.bindings||{};}dispatchFetch(url,init){return this.worker.fetch(new Request(url,init),this.env);}async dispose(){}}
let result={success:true,hostname:'agent.phdirectory.net',action:'login'},verifyCalls=0,credentialCalls=0,unavailable=false;
const mf=new Miniflare({modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-07-01',bindings:{TURNSTILE_SECRET_KEY:'private-test-secret'},outboundService:async req=>{if(req.url==='https://challenges.cloudflare.com/turnstile/v0/siteverify'){verifyCalls++;const data=await req.json();assert.equal(data.secret,'private-test-secret');assert.equal(req.headers.get('Authorization'),null);if(unavailable)return new Response('Unavailable',{status:503});return Response.json(result);}credentialCalls++;return new Response('QA Report ALL XFER');}});
const login=token=>mf.dispatchFetch('https://agent.phdirectory.net/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'test',password:'test-password',date:'2026-10-07',turnstileToken:token})});
try{
 const config=await (await mf.dispatchFetch('https://agent.phdirectory.net/api/login-config')).json();assert.equal(config.enabled,true);assert.equal(config.siteKey,'0x4AAAAAAEkUwlNfuu-QzxQZ');assert.equal(JSON.stringify(config).includes('private-test-secret'),false);
 assert.equal((await login()).status,400);assert.equal((await login('x'.repeat(2049))).status,400);assert.equal(verifyCalls,0);assert.equal(credentialCalls,0);
 for(const bad of [{success:false,'error-codes':['timeout-or-duplicate']},{success:true,hostname:'evil.example',action:'login'},{success:true,hostname:'agent.phdirectory.net',action:'other'}]){result=bad;assert.equal((await login('test-token')).status,403);}assert.equal(credentialCalls,0);
 unavailable=true;assert.equal((await login('test-token')).status,503);assert.equal(credentialCalls,0);unavailable=false;result={success:true,hostname:'agent.phdirectory.net',action:'login'};const accepted=await login('test-token');assert.equal(accepted.status,200);assert.equal(credentialCalls,1);const cookie=accepted.headers.get('Set-Cookie').split(';')[0];assert.equal((await mf.dispatchFetch('https://agent.phdirectory.net/api/session',{headers:{Cookie:cookie}})).status,200);assert.equal(credentialCalls,1);
 const csp=(await mf.dispatchFetch('https://agent.phdirectory.net/')).headers.get('Content-Security-Policy');assert.match(csp,/frame-src https:\/\/challenges.cloudflare.com/);
}finally{await mf.dispose();}
const unconfigured=new Miniflare({modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-07-01',outboundService:()=>{throw Error('Must not reach upstream');}});try{const response=await unconfigured.dispatchFetch('http://localhost/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'test',password:'test-password',date:'2026-10-07',turnstileToken:'token'})});assert.equal(response.status,503);}finally{await unconfigured.dispose();}
console.log('PASS: Turnstile requires tokens, validates hostname/action, rejects replay/expiry and outages, hides secrets, fails closed without configuration and preserves sessions.');
// Exercise browser challenge state: submit only after success; reset consumed tokens on errors.
const app=readFileSync('app.js','utf8'),elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,{value:id==='date'?'2026-10-07':'test',textContent:'',className:'',hidden:false,disabled:false});return elements.get(id);};let widgetOptions,resets=0,loginBodies=[];
const ui=vm.createContext({$,window:{turnstile:{render:(selector,options)=>{widgetOptions=options;return 1;},reset:()=>{resets++;},remove:()=>{}}},setTimeout,clearTimeout,authorization:false,showDashboard:()=>{},fetch:async(url,options)=>{if(url==='/api/login-config')return Response.json({enabled:true,siteKey:'public-key',appName:'Example Monitoring'});loginBodies.push(JSON.parse(options.body));return Response.json({error:'Wrong credentials'},{status:401});}});
vm.runInContext(app.slice(app.indexOf("$('login').onsubmit="),app.indexOf('async function restoreSession'))+app.slice(app.indexOf("let configuredAppName="),app.indexOf('restoreSession();')),ui);
await ui.initializeLoginChallenge();assert.equal($('app-brand').textContent,'Example Monitoring');assert.equal($('login-app-name').textContent,'Example Monitoring');assert.equal($('login-app-footer').textContent,'Example Monitoring');assert.equal($('sign-in').disabled,true);await $('login').onsubmit({preventDefault(){}});assert.equal(loginBodies.length,0);widgetOptions.callback('verified-token');assert.equal($('sign-in').disabled,false);widgetOptions['expired-callback']();assert.equal($('sign-in').disabled,true);widgetOptions.callback('another-token');await $('login').onsubmit({preventDefault(){}});assert.equal(loginBodies[0].turnstileToken,'another-token');assert.equal(resets,1);assert.equal($('sign-in').disabled,true);widgetOptions['error-callback']();assert.equal($('retry-verification').hidden,false);await $('retry-verification').onclick();assert.equal($('retry-verification').hidden,true);console.log('PASS: login widget gates submission, handles expiry/errors, retries and resets consumed tokens after failed credentials.');
